import TabMenu from "./components/TabMenu";
import "./globals.css";
import "@splidejs/splide/dist/css/splide.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "./public/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <nav className="w-[244px] border-r-2 h-screen fixed top-0 left-0 p-2">
            <TabMenu />
          </nav>
          <div className="w-[80%] ml-[284px] ">{children}</div>
        </div>
      </body>
    </html>
  );
}
